(function(){
const qs=new URLSearchParams(location.search),VIEW=qs.get('view')==='1';
const S={draft:'Черновик',review:'Нужно проверить',ready:'Готово',ingame:'В игре',cut:'Вырезано'};
const E=x=>(0,eval)(x), H=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ready=false,lastNodeKey='',lastRightId='',lastFavKey='';
function st(){return E('state')}function sid(){return E('selected')}function nd(id){return st().nodes.find(n=>n.id===id)}function save(){try{E('saveLocal()')}catch(e){}}function lbl(v){return S[v||'draft']||'Черновик'}
function meta(){let s=st();s.meta=s.meta||{};s.meta.history=s.meta.history||[];return s.meta}function log(a,d){let m=meta();m.history.unshift({time:new Date().toISOString(),user:localStorage.getItem('bezdna_user_name')||'Локально',action:a,details:d||''});m.history=m.history.slice(0,80);save()}
function defaults(){for(const n of st().nodes){if(!n.status)n.status='draft';if(typeof n.favorite!=='boolean')n.favorite=false}}
function left(){if(document.getElementById('featureTools'))return;let s=document.getElementById('search');if(!s)return;let d=document.createElement('div');d.id='featureTools';d.innerHTML='<h2>Удобства</h2><div class="stack feature-stack"><button class="btn" id="mdBtn">Экспорт Markdown</button><button class="btn" id="histBtn">История действий</button><button class="btn" id="bakBtn">Авто-бэкапы</button><a class="btn ghost" target="_blank" href="?project='+(window.BEZDNA_PROJECT||'bezdna-main')+'&view=1">Открыть просмотр</a></div><h2>Избранное</h2><div id="favoritesBox" class="row"></div>';s.parentNode.insertBefore(d,s.nextSibling);document.getElementById('mdBtn').onclick=md;document.getElementById('histBtn').onclick=historyPanel;document.getElementById('bakBtn').onclick=()=>pop('Авто-бэкапы','<p>При нажатии <b>Сохранить всем</b> создаётся резервная копия проекта отдельным JSON в GitHub.</p>')}
function favs(){let b=document.getElementById('favoritesBox');if(!b)return;let arr=st().nodes.filter(n=>n.favorite),key=arr.map(n=>n.id).join('|');if(key===lastFavKey)return;lastFavKey=key;b.innerHTML=arr.length?arr.map(n=>'<button class="btn small ghost" data-fav="'+H(n.id)+'">★ '+H(n.title)+'</button>').join(''):'<span class="tiny">Пока нет избранных.</span>';b.querySelectorAll('[data-fav]').forEach(x=>x.onclick=()=>E('selected='+JSON.stringify(x.dataset.fav)+';render();center()'))}
function badges(){let key=st().nodes.map(n=>n.id+':'+(n.status||'')+':'+(n.favorite?'1':'0')).join('|');if(key===lastNodeKey)return;lastNodeKey=key;let byTitle=new Map(st().nodes.map(n=>[n.title,n]));document.querySelectorAll('.node').forEach(el=>{let n=byTitle.get(el.querySelector('.title')?.textContent||'');if(!n)return;el.classList.toggle('fav-node',!!n.favorite);el.classList.remove('status-draft','status-review','status-ready','status-ingame','status-cut');el.classList.add('status-'+(n.status||'draft'));let b=el.querySelector('.feature-badges');if(!b){b=document.createElement('div');b.className='feature-badges';el.appendChild(b)}b.innerHTML=(n.favorite?'<span class="chip favchip">★</span>':'')+'<span class="chip status status-'+(n.status||'draft')+'">'+H(lbl(n.status))+'</span>'})}
function right(){let r=document.getElementById('right'),n=nd(sid());if(!r||!n||lastRightId===n.id&&r.querySelector('#featureNodeTools'))return;lastRightId=n.id;let old=r.querySelector('#featureNodeTools');if(old)old.remove();let c=document.createElement('div');c.id='featureNodeTools';c.className='card feature-node-tools';c.innerHTML='<div class="row space"><button class="btn small '+(n.favorite?'gold':'ghost')+'" id="favToggle">'+(n.favorite?'★ В избранном':'☆ В избранное')+'</button><label class="tiny">Статус<select class="field" id="statSel">'+Object.entries(S).map(([v,l])=>'<option value="'+v+'" '+(v===(n.status||'draft')?'selected':'')+'>'+l+'</option>').join('')+'</select></label></div>';r.insertBefore(c,r.children[1]||r.firstChild);c.querySelector('#favToggle').onclick=()=>{n.favorite=!n.favorite;log(n.favorite?'Добавлено в избранное':'Удалено из избранного',n.title);lastNodeKey='';lastFavKey='';E('render()')};c.querySelector('#statSel').onchange=e=>{n.status=e.target.value;log('Изменён статус',n.title+': '+lbl(n.status));lastNodeKey='';E('render()')}}
function md(){let out=['# Бездна','','Экспорт: '+new Date().toLocaleString('ru-RU'),''];for(const n of st().nodes.slice().sort((a,b)=>a.x-b.x)){out.push('## '+(n.favorite?'★ ':'')+n.title,'','- Статус: '+lbl(n.status),'- NPC: '+(n.npc||''),'- Локация: '+(n.loc||''),'',n.summary||'','');for(const o of n.obj||[])out.push('- '+o);let ds=st().dialogs[n.id]||[];if(ds.length){out.push('','### Диалог');for(const d of ds){out.push('**'+(d.speaker||'NPC')+':** '+(d.text||''));for(const c of d.choices||[])out.push('- Игрок: '+(c.text||''))}}out.push('')}let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out.join('\n')],{type:'text/markdown'}));a.download='bezdna_scenario.md';a.click()}
function pop(t,b){let m=document.getElementById('featureModal');if(!m){m=document.createElement('div');m.id='featureModal';m.innerHTML='<div class="feature-modal-box"><div class="row space"><h2 id="featureModalTitle"></h2><button class="btn red" id="featureClose">Закрыть</button></div><div id="featureModalBody"></div></div>';document.body.appendChild(m);document.getElementById('featureClose').onclick=()=>m.classList.remove('open')}document.getElementById('featureModalTitle').textContent=t;document.getElementById('featureModalBody').innerHTML=b;m.classList.add('open')}
function historyPanel(){let h=meta().history||[];pop('История действий',h.length?h.map(i=>'<div class="card"><b>'+H(i.action)+'</b><br><span class="tiny">'+new Date(i.time).toLocaleString('ru-RU')+'</span><p>'+H(i.details||'')+'</p></div>').join(''):'<p class="tiny">История пока пустая.</p>')}
async function backup(){if(VIEW||typeof workerRequest!=='function')return;try{let p=window.BEZDNA_PROJECT||'bezdna-main',x='backup_'+p+'_'+new Date().toISOString().slice(0,16).replace('T','_').replace(':','-');await workerRequest('/api/project?project='+encodeURIComponent(x),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:x,key:workerKey(),user:workerUser(),state:st()})});log('Создан авто-бэкап',x)}catch(e){console.warn(e)}}
function wrapSave(){setTimeout(()=>{if(window.__fxwrap||typeof saveGitHub!=='function')return;window.__fxwrap=true;let old=saveGitHub;window.saveGitHub=async function(){let r=await old.apply(this,arguments);backup();return r}},1000)}
function view(){if(!VIEW)return;document.body.classList.add('view-only');let warn=()=>alert('Это режим просмотра. Редактирование отключено.');['saveGitHub','uploadFile','saveQuest','addNode','delNode','addLine','addChoice','delLine'].forEach(k=>window[k]=warn)}
function search(){let box=document.getElementById('search');if(!box||box.dataset.fx)return;box.dataset.fx='1';box.addEventListener('input',()=>{let q=box.value.toLowerCase();if(!q)return;document.querySelectorAll('.mini').forEach(x=>{let txt=x.textContent.toLowerCase();x.style.display=txt.includes(q)?'':'none'})},true)}
function tick(){if(!ready)return;defaults();left();badges();right();favs();search()}
function init(){ready=true;defaults();left();wrapSave();view();tick();setInterval(tick,1400);log('Открыт проект',location.href)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
