(function(){
  if(new URLSearchParams(location.search).get('view')==='1')return;
  const PROJECT=window.BEZDNA_PROJECT||new URLSearchParams(location.search).get('project')||'bezdna-main';
  let myId=null,ws=null,rev=0,connected=false,users=[],locks={},sendTimer=null,ignore=false,lastSent='',lastSelected=null,reconnectTimer=null;
  const run=code=>(0,eval)(code);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function getState(){return run('state')}
  function getSelected(){return run('selected')}
  function node(id){return getState().nodes.find(n=>n.id===id)}
  function userName(){return localStorage.getItem('bezdna_user_name')||'Гость'}
  function liveUrl(){const base=(window.BEZDNA_WORKER_URL||'https://saitna.xomein0165.workers.dev').replace(/^http/,'ws');return base+'/api/live?project='+encodeURIComponent(PROJECT)+'&user='+encodeURIComponent(userName())}
  function setStatus(t){try{status(t)}catch(e){console.log(t)}}
  function send(obj){if(ws&&ws.readyState===1)ws.send(JSON.stringify(obj))}
  function stateJson(){try{const s=getState();s.selectedId=getSelected();return JSON.stringify(s)}catch(e){return ''}}
  function applyFull(next){if(!next||typeof next!=='object')return;ignore=true;try{run('state='+JSON.stringify(next)+';selected=state.selectedId||selected||state.nodes?.[0]?.id;localStorage.setItem("bezdna_state_v3",JSON.stringify(state));render();')}finally{setTimeout(()=>ignore=false,120)}}
  function applyPatch(msg){ignore=true;try{const s=getState();if(msg.kind==='move_node'){const n=node(msg.nodeId);if(n){n.x=msg.x;n.y=msg.y}}else if(msg.kind==='update_node'){const n=node(msg.nodeId);if(n)Object.assign(n,msg.patch||{})}else if(msg.kind==='update_dialog'){s.dialogs=s.dialogs||{};s.dialogs[msg.nodeId]=Array.isArray(msg.dialogs)?msg.dialogs:[]}else if(msg.kind==='add_link'){s.links=s.links||[];const l=msg.link||{};const i=s.links.findIndex(x=>x.id===l.id||(x.from===l.from&&x.to===l.to&&x.label===l.label));if(i>=0)s.links[i]=Object.assign({},s.links[i],l);else s.links.push(Object.assign({id:'live_'+Date.now(),type:'branch',label:''},l))}localStorage.setItem('bezdna_state_v3',JSON.stringify(s));run('render()')}finally{setTimeout(()=>ignore=false,120)}}
  function renderLiveBox(){let box=document.getElementById('liveBox');if(!box){const statusEl=document.getElementById('status');const card=statusEl&&statusEl.closest('.card');if(!card)return;box=document.createElement('div');box.id='liveBox';box.className='liveBox';card.appendChild(box)}box.innerHTML='<b>Live-онлайн</b><div class="liveState">'+(connected?'подключено':'не подключено')+' · rev '+rev+'</div><div class="liveUsers">'+(users.length?users.map(u=>'<span class="liveUser">'+esc(u.name)+(u.id===myId?' · ты':'')+'</span>').join(''):'<span class="tiny">пока никого</span>')+'</div><div class="row" style="margin-top:8px"><button class="btn small" id="liveBackupBtn">GitHub-бэкап</button><button class="btn small" id="liveReconnectBtn">Переподключить</button></div>';document.getElementById('liveBackupBtn').onclick=()=>send({type:'save_backup'});document.getElementById('liveReconnectBtn').onclick=()=>connect(true)}
  function lockedByOther(id){const l=locks&&locks[id];return l&&l.by!==myId?l:null}
  function markLocks(){document.body.classList.toggle('live-readonly-selected',Boolean(lockedByOther(getSelected())));document.querySelectorAll('.node').forEach(el=>{const title=el.querySelector('.title')?.textContent||'';const n=getState().nodes.find(x=>x.title===title);if(!n)return;const l=lockedByOther(n.id);el.classList.toggle('live-locked',Boolean(l));let chip=el.querySelector('.liveLockChip');if(l&&!chip){chip=document.createElement('span');chip.className='chip liveLockChip';el.appendChild(chip)}if(l&&chip)chip.textContent='редактирует: '+l.name;if(!l&&chip)chip.remove()});const right=document.getElementById('right');if(right){let old=document.getElementById('liveLockWarn');const l=lockedByOther(getSelected());if(l&&!old){old=document.createElement('div');old.id='liveLockWarn';old.className='liveWarn';right.insertBefore(old,right.firstChild)}if(l&&old)old.textContent='Этот узел сейчас редактирует '+l.name+'. Лучше не менять его одновременно.';if(!l&&old)old.remove()}}
  function lockSelected(){const id=getSelected();if(id&&id!==lastSelected){if(lastSelected)send({type:'unlock',nodeId:lastSelected});lastSelected=id;send({type:'lock',nodeId:id})}}
  function pushFullSoon(){if(ignore||!connected)return;clearTimeout(sendTimer);sendTimer=setTimeout(()=>{const json=stateJson();if(!json||json===lastSent)return;lastSent=json;send({type:'full_state',state:JSON.parse(json),note:'client_change'})},700)}
  function tryMovePatch(){if(ignore||!connected)return;const id=getSelected();const n=node(id);if(!id||!n)return;send({type:'patch',kind:'move_node',nodeId:id,x:n.x,y:n.y})}
  function onMessage(e){let msg;try{msg=JSON.parse(e.data)}catch(_){return}if(msg.type==='hello'){myId=msg.id;rev=msg.rev||0;users=msg.users||[];locks=msg.locks||{};applyFull(msg.state);lastSent=stateJson();connected=true;setStatus('Live-онлайн подключён');renderLiveBox();markLocks();return}if(msg.type==='presence'){users=msg.users||users;locks=msg.locks||locks;renderLiveBox();markLocks();return}if(msg.type==='locks'){locks=msg.locks||{};markLocks();return}if(msg.type==='state'){rev=msg.rev||rev;applyFull(msg.state);lastSent=stateJson();setStatus('Live: обновление от '+(msg.by||'участника'));markLocks();return}if(msg.type==='patch'){rev=msg.rev||rev;applyPatch(msg);setStatus('Live: правка от '+(msg.by||'участника'));markLocks();return}if(msg.type==='lock_denied'){setStatus('Узел редактирует '+msg.owner);return}if(msg.type==='backup'){setStatus('GitHub-бэкап: '+(msg.by||'live'));return}if(msg.type==='backup_error'){setStatus('Ошибка live-бэкапа: '+msg.error);return}}
  function connect(force){if(ws&&ws.readyState===1&&!force)return;if(ws)try{ws.close()}catch(_){};clearTimeout(reconnectTimer);connected=false;renderLiveBox();try{ws=new WebSocket(liveUrl());ws.onopen=()=>{connected=true;renderLiveBox();send({type:'ping'})};ws.onmessage=onMessage;ws.onclose=()=>{connected=false;renderLiveBox();reconnectTimer=setTimeout(()=>connect(false),3000)};ws.onerror=()=>{connected=false;renderLiveBox()}}catch(e){connected=false;renderLiveBox();reconnectTimer=setTimeout(()=>connect(false),5000)}}
  function install(){renderLiveBox();connect(false);document.addEventListener('input',()=>{lockSelected();pushFullSoon()},true);document.addEventListener('change',()=>{lockSelected();pushFullSoon()},true);document.addEventListener('pointerdown',()=>setTimeout(lockSelected,60),true);document.addEventListener('pointerup',()=>{lockSelected();tryMovePatch();pushFullSoon()},true);setInterval(()=>{lockSelected();markLocks();renderLiveBox()},1500);setInterval(()=>send({type:'ping'}),25000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,500));else setTimeout(install,500);
})();
