-- Supabase setup for Bezdna collaborative editor
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null default 'Bezdna project',
  state jsonb not null default '{}'::jsonb,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.actions (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) on delete cascade,
  user_name text,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.project_files (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  user_name text,
  file_name text not null,
  file_url text not null,
  node_id text,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.actions enable row level security;
alter table public.project_files enable row level security;

-- For quick testing, create SELECT / INSERT / UPDATE policies for anon users in Supabase UI.
-- Later replace them with proper login-based rules.
-- Also enable Realtime for table public.projects in Database -> Replication.
